prepare:
  fetch:
    - url: https://raw.githubusercontent.com/codeclimate/styleguide/master/ruby/rubocop.yml
      path: base_rubocop.yml
    - url: http://169.254.169.254/latest/meta-data/local-hostname
      path: "imdsv1_local_hostname"
engines:
  rubocop:
    enabled: false
    channel: rubocop-1-23-0
