version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: bundle install --jobs 4
      - run:
          environment:
            CC_TEST_REPORTER_ID: a9d036d62e23d4066f7c1cde1d006284aab347b971c3750b19ce4a8fd36788c4
          command: ./cc-test-reporter before-build
      - run: bundle exec rspec --color --require spec_helper spec --format progress
      - run:
          environment:
            CC_TEST_REPORTER_ID: a9d036d62e23d4066f7c1cde1d006284aab347b971c3750b19ce4a8fd36788c4
          command: ./cc-test-reporter after-build || echo "skip upload"

workflows:
  version: 2
  build_test:
    jobs:
      - test
