version: 2

jobs:
  test:
    docker:
      - image: circleci/ruby
    steps:
      - checkout
      - run: curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > cc-test-reporter
      - run: chmod +x ./cc-test-reporter
      - run: bundle install --jobs 4
      - run:
          environment:
            CC_TEST_REPORTER_ID: 97d8ebc3cb7691505bc2ff67e7fb70769bb8bcf798b1614895c71f1adc4df4a8
          command: ./cc-test-reporter before-build
      - run: bundle exec rspec --color --require spec_helper spec --format progress
      - run:
          environment:
            CC_TEST_REPORTER_ID: 97d8ebc3cb7691505bc2ff67e7fb70769bb8bcf798b1614895c71f1adc4df4a8
          command: ./cc-test-reporter after-build || echo "skip upload"

workflows:
  version: 2
  build_test:
    jobs:
      - test
